### ISSUE TITLE
Build changes the owner of files to root

### ISSUE THREAD

**Issue by Vorlif** [techknowlogick/xgo#10]
Hi, thanks for extending the package.

I tested your version today and found that it changes the permissions of a few files on my system.

After the build, the following files were assigned to the `root` user:
* go.sum
* go.mod
* All created executable files
* A few dependencies in `$GOPATH/pkg`

After that I could no longer build without xgo because I lacked the necessary permissions.

My system:
* Arch Linux
* go 1.12.1
* with go modules

I think it would be best if xgo does not change the owner, but instead takes over the current one.

**Comment by kolaente** [comment]
The build happens in a docker container, which runs as root. As a result, all built binariers are owned by root. 
xgo probably made changes on `go.mod` and `go.sum` because it downloaded some dependencies and pinned them in the `go.mod` and `go.sum` files. To prevent this you should ensure all dependencies are already in those files before building with xgo.

**Comment by kolaente** [comment]
> After that I could no longer build without xgo because I lacked the necessary permissions.

Was there an error message? (most likely your current user couldn't access `go.mod`?)

**Comment by Vorlif** [comment]
Thanks for the quick reply.

> Was there an error message? (most likely your current user couldn't access go.mod?)

That's exactly the problem. I had to manually change the user back again.

**Comment by kolaente** [comment]
> That's exactly the problem. I had to manually change the user back again.

That's something which can most likely be fixed with building the programm manually (`go build ...`) before running xgo. That way, xgo won't (or at least shouldn't) modify the file. Could you check that?

**Comment by techknowlogick** [comment]
I wonder if we could have xgo pass current user via `--user` flag that way current permissions would hopefully be retained.

More info on user flag: https://docs.docker.com/engine/reference/run/#user

**Comment by bearsh** [comment]
another way would be to simply call something like the following at the end:
```bash
chown -R --reference . $OUTPUT_FOLDER
```
this changes ownership of all files in `$OUTPUT_FOLDER` to the user owning the current directory (assuming the current directory is the project directory)

**Comment by techknowlogick** [comment]
closed per linked PR
