### ISSUE TITLE
xgo 1.16 fails to crosscompile darwin/amd64

### ISSUE THREAD

**Issue by m90** [techknowlogick/xgo#100]
I'm cross-compiling an application using xgo. After migrating to go-1.16 building `darwin/amd64` fails with the following error:

```
#85 82.23 Undefined symbols for architecture x86_64:
#85 82.23   "_clock_gettime", referenced from:
#85 82.23       _runtime.walltime_trampoline in go.o
#85 82.23 ld: symbol(s) not found for architecture x86_64
#85 82.23 clang: error: linker command failed with exit code 1 (use -v to see invocation)
#85 82.23 
#85 82.27 2021/02/17 19:35:02 Failed to cross compile package: exit status 2.
```

Windows and Linux for amd64 (I do not target other architectures currently) still build.

My build command looks like this:

```
RUN xgo --targets=darwin/amd64 --tags 'osusergo netgo static_build sqlite_omit_load_extension' --ldflags="-linkmode external -extldflags '' -s -w -X github.com/offen/offen/server/config.Revision=485f7f7" github.com/offen/offen/server/cmd/offen:
```

Is this specific to the code I am trying to compile or is this a general problem in the 1.16 version of xgo?

**Comment by kolaente** [comment]
We're already investigating this in https://github.com/techknowlogick/xgo/pull/99

Looks like this is a general problem with the 1.16 version of xgo.

**Comment by kolaente** [comment]
After a lengthy git bisect with the go code, I was able to identify the commit in the go source that introduced the issue: https://github.com/golang/go/commit/ae76f6e96216f352cc5021a4c8a7d879c4cb6873

It looks like it makes sense it fails since it introduces a call to a macos api which is available since 10.12, we're on 10.11 iirc.

**Comment by kolaente** [comment]
Looks like [the release notes for 1.15](https://golang.org/doc/go1.15#darwin) already say that go now requires at least mac os 10.12 so it really has been just luck so far that it didn't break earlier

**Comment by m90** [comment]
I ran into https://github.com/techknowlogick/xgo/issues/79 (which I strangely should have encountered before, but didn't) after pulling the updates from #99 but got things working again with Go 1.16 now. Thank you for maintaining xgo!

**Comment by kolaente** [comment]
Ah yes, the kind of issues where I had a problem, opened an issue, debugged the problem in public and fixed it are the best 😂
