### ISSUE TITLE
Executables with dots in name show as "Document" on OSX

### ISSUE THREAD

**Issue by grv99** [techknowlogick/xgo#102]
A minor one - OSX shows executables as "Document" or "Terminal Document" in Finder when the file has an unknown extension. Can be solved by replacing the dots with hyphen (or underscore). The file still executes as normal on double click, but it doesn't look good and satisfying 😄

**Comment by techknowlogick** [comment]
Thanks for this issue, as this is a breaking change I am hesitant to accept the PR as some downstream users expect a certain file path upon build, and I don't want to break that implicit promise with them.
