### ISSUE TITLE
xgo fails to build with go-1.16.0

### ISSUE THREAD

**Issue by darkn3rd** [techknowlogick/xgo#104]
Currently with the default `GO111MODULE=""` and `xgo -go=go-1.16.0` (`techknowlogick/xgo:go-1.16.0`), this will fail.  

When using `xgo -go=go-1.15.8` (`techknowlogick/xgo:go-1.15.8`), this works fine.

## Expected Results

I expected that `techknowlogick/xgo:go-1.16.0` would succeed.

## Actual Results

```
go: cannot find main module; see 'go help modules'
2021/03/01 01:01:30 Failed to cross compile package: exit status 1.
```

## Workaround

```bash
cat <<-EOF > xgo.Dockerfile
FROM techknowlogick/xgo:go-1.16.0
RUN go env -w GO111MODULE=auto
EOF
docker build -f xgo.Dockerfile -t happybuilds/xgo:1.16 .
xgo -image happybuilds/xgo:1.16 ... 
```

## Links

* https://blog.golang.org/go116-module-changes

**Comment by techknowlogick** [comment]
Closing, as per the link you sent this is due to upstream go changes. I'm thinking about a possible new cli argument for env vars where you can pass arbitrary envs though.

**Comment by darkn3rd** [comment]
I wonder if `xgo` by reading `go.mod` detects that GO111MODULE is not used incorrectly, then branches down a different method, uniquely causes this problem.  The fact that `xgo` will not work for 1.16 can be problematic, especially when falsely detecting that GO111MODULE is not used.
