### ISSUE TITLE
Cache build results across xgo runs

### ISSUE THREAD

**Issue by leventov** [techknowlogick/xgo#108]
xgo compilation is very slow because it uses `go build` internally, [which doesn't cache cgo compilation results](https://stackoverflow.com/questions/32061750/go-build-rebuilds-unnecessarily).

Maybe we can mount ~/.xgo-cache/<platform> as `GOCACHE` directory within the container, which will be reused across xgo runs?

**Comment by makeworld-the-better-one** [comment]
I'm pretty sure `go build` does cache CGo compilation results, I've seen it happen. It's probably just that the cache happens in a container and gets removed.

**Comment by leventov** [comment]
We fixed this, it was quite easy.

It amounted into just the following changes:

1) adding to `compile()` function in `xgo.go`:

```go
gocache := filepath.Join(depsCache, "gocache")
if err := os.MkdirAll(gocache, 0777); err != nil {
	log.Fatalf("Failed to create gocache dir: %v.", err)
}
gocache_w := filepath.ToSlash(re.ReplaceAllString(gocache, "/$1"))

...
"-v", gocache_w + ":/gocache:rw",
```

2) adding some lines in `build.sh`:

```
mkdir -p /gocache/linux/amd64
GOCACHE=/gocache/linux/amd64 go build...
```

@techknowlogick should I create a PR or you would like to implement it the way you want?

**Comment by leventov** [comment]
@techknowlogick what do you think about this?

**Comment by aadog** [comment]
Why is he missing again

**Comment by aadog** [comment]
Has the submission not been merged？
