### ISSUE TITLE
go: go.mod file not found in current directory or any parent directory

### ISSUE THREAD

**Issue by rleighton** [techknowlogick/xgo#109]
I get: 
```
go: go.mod file not found in current directory or any parent directory
```

However:
```
bash-3.2$ ls go.mod
go.mod
```

The command: 
```
xgo -x --deps https://www.sqlite.org/2020/sqlite-autoconf-3320300.tar.gz --depsargs '--disable-fts4 --disable-fts5 --disable-rtree --disable-static-shell' --pkg internal/log_analysis/datalake/database_api/snowflake/driver/main --targets=linux/amd64 -out main --tags 'libsqlite3 linux' -dest out/bin/internal/log_analysis/datalake/database_api/snowflake/driver/main .
```

Any ideas?

This worked with go 1.13 but now I have to move to 1.16 because of other changes in the code base.

**Comment by techknowlogick** [comment]
Do you have an example repo that I could try this on?

**Comment by rleighton** [comment]
Found the issue , tiny PR coming. The change is specific to a local build.

**Comment by rleighton** [comment]
I don't have permissions to post a PR. This is the diff: 
```
commit 66c5a7348e45f209e851114ae735bd53f37f1ec6 (HEAD -> russ-fix-local-module-builds)
Author: Russell Leighton <russell.leighton@runpanther.io>
Date:   Sat Mar 20 07:10:31 2021 -0400

    Fix repo path setting bug for local builds

diff --git a/xgo.go b/xgo.go
index a341db0..961ecaf 100644
--- a/xgo.go
+++ b/xgo.go
@@ -255,19 +255,19 @@ func compile(image string, config *ConfigFlags, flags *BuildFlags, folder string
        locals, mounts, paths := []string{}, []string{}, []string{}
        var usesModules bool
        if strings.HasPrefix(config.Repository, string(filepath.Separator)) || strings.HasPrefix(config.Repository, ".") {
-               // Resolve the repository import path from the file path
-               config.Repository = resolveImportPath(config.Repository)
-
                // Determine if this is a module-based repository
-               var modFile = config.Repository + "/go.mod"
-               _, err := os.Stat(modFile)
-               usesModules = !os.IsNotExist(err)
+               if _, err := os.Stat(config.Repository + "/go.mod"); err == nil {
+                       usesModules = true
+               }
 
                // Iterate over all the local libs and export the mount points
                if os.Getenv("GOPATH") == "" && !usesModules {
                        log.Fatalf("No $GOPATH is set or forwarded to xgo")
                }
                if !usesModules {
+                       // Resolve the repository import path from the file path
+                       config.Repository = resolveImportPath(config.Repository)
+
                        for _, gopath := range strings.Split(os.Getenv("GOPATH"), string(os.PathListSeparator)) {
                                // Since docker sandboxes volumes, resolve any symlinks manually
                                sources := filepath.Join(gopath, "src")

```

**Comment by rleighton** [comment]
> I don't but thanks for asking. If I can't sort this maybe I can craft one.
> 
> I'm wondering if it is related to any of this new 1.16 changes: https://blog.golang.org/go116-module-changes.
> 
> Interestingly, if I run with `-go go-1.15.10` it works BUT my application uses the new 1.16 embed feature and so it fails build.

1.15 worked because I had GOPATH set.

**Comment by techknowlogick** [comment]
Awesome, thanks :) Let me try to put this together as a PR.

**Comment by rleighton** [comment]
Do have an idea when this might merge? We have obviously a working forked version but it would make our builds easier when this is updated. Thank you !

**Comment by serbantanasa** [comment]
Hi @techknowlogick @rleighton I've hit this issue two -- seems to be a 6 line fix. I'd push a PR but don't have the permissions.

**Comment by serbantanasa** [comment]
any news?

**Comment by rleighton** [comment]
ping?

**Comment by thebaer** [comment]
I'm seeing same issue in our [WriteFreely](https://github.com/writefreely/writefreely) project... Running this command produces the same error, despite there being a `go.mod` file in the current directory where this is being run from:

```
xgo --targets=linux/amd64, -dest build/ -tags='sqlite' -out writefreely ./cmd/writefreely
```

Not sure if we need to change the command, or if this is a bug in `xgo`, but this used to work.

**Comment by makeworld-the-better-one** [comment]
@thebaer It's a bug in xgo. You can use the patch above, or just run xgo with go1.15 instead of 1.16.

**Comment by thebaer** [comment]
Thanks! Adding `-go go-1.15.x` fixed this for me.

**Comment by darkn3rd** [comment]
I am not sure if related, but I ran into issues with xgo and go 1.16 that requires `GO111MODULE=auto`.  So I created my own image:
```Dockerfile
ARG GOVERSION=1.16.0
FROM techknowlogick/xgo:go-${GOVERSION}
# https://github.com/techknowlogick/xgo/issues/104
RUN go env -w GO111MODULE=auto
```

And during build process:

```bash
docker build -f release/xgo.Dockerfile -t dgraph/xgo:go-${GOVERSION} --build-arg GOVERSION=${GOVERSION} .
export XGO_IMAGE_OPT="-image dgraph/xgo:go-${GOVERSION}"
xgo -x -go="go-$GOVERSION" --targets= linux/$GOARCH $XGO_IMAGE_OPT -buildmode=exe .
```

**Comment by techknowlogick** [comment]
I've just created https://github.com/techknowlogick/xgo/pull/121 using the patch above, and will merge it hopefully once tests pass.

**Comment by jyap808** [comment]
Test case fails. See PR for more details.

**Comment by beastawakens** [comment]
Would really appreciate getting this in, causing me a lot of pain at the moment!

**Comment by techknowlogick** [comment]
Closing as linked PR has now been merged. Will be a sec before CI builds/publishes the new images.

**Comment by jyap808** [comment]
This still fails for the ethereum/go-ethereum test case. More so it produces and incorrect binary.

```
$ stat github.com/ethereum/go-ethereum-linux-amd64
  File: github.com/ethereum/go-ethereum-linux-amd64
  Size: 151904          Blocks: 304        IO Block: 4096   regular file

$ file github.com/ethereum/go-ethereum-linux-amd64
github.com/ethereum/go-ethereum-linux-amd64: current ar archive
```

**Comment by beastawakens** [comment]
Yeah, I updated to the latest image and it still produces the same error for me (`go: go.mod file not found in current directory or any parent directory`) 😞

**Comment by techknowlogick** [comment]
oh darn, thanks for letting me know. I've reopened this so I can look into it.

**Comment by techknowlogick** [comment]
ok, I've been looking at this a bit.

I was missing a bit of the puzzle, https://github.com/techknowlogick/xgo/blob/main/xgo.go#L261 looks to see if the directory that is passed has a go mod, however as mentioned above this fails for the geth case (where the go.mod file is in a parent). From my debugging the reason for that is  /tmp/eth/cmd/geth is the path mounted into the container, not /tmp/eth (which is the directory with go.mod). I suspect that using `go env GOMOD`, mounting in the path with go.mod, then building from requested subdir is the appropriate solution.
