### ISSUE TITLE
 Executable not found 

### ISSUE THREAD

**Issue by fuadahsan** [techknowlogick/xgo#129]
When I try to run the compiled executable (I am targeting linux/mipsle) using './', I get the error " ./datsync-linux-mipsle: not found".(datsync is the name of my program) I have tried targeting darwin/amd64 (my Mac) and that works fine. Am I missing something with the linux/mipsle target? Any help is appreciated.

**Comment by techknowlogick** [comment]
Thanks for opening this issue, can you give the CLI command you are using to call xgo, and do you have an example repo that I could reference?

**Comment by jsw-davidhuang** [comment]
i got this issue too, any solution for this?

**Comment by techknowlogick** [comment]
@jsw-davidhuang are you able to answer the questions in my previous comment? I require more details to be able to assist.

**Comment by jsw-davidhuang** [comment]
i see, now i use the command , un ubuntu 20, go version: 1.16.5
```
sudo ~/gopath/bin/xgo ~/Desktop/testgo
```
then i make all platform of binary file, i test the windows file is working good; but i send the mipsle file to my camera(mipsle system) then show the hint. 
before that, i use go cross compile the mipsle to run is working(pure go code)

**Comment by jsw-davidhuang** [comment]
i can offer the screencut
![image](https://user-images.githubusercontent.com/88757436/155471726-96609d15-20a0-4283-abe1-538f52c16692.png)

**Comment by fghjhuang** [comment]
hey @techknowlogick @fuadahsan  i think i found a solution to solve this issue, when using xgo to build, xgo need to build it as static, cause when move the Executable file into a system like mips/mipsle/mipsle64, they usually not include glibc in it. so make a static & Executable file is necessary ， so i suggest xgo to add an option to make static file:
```
-a -ldflags '-extldflags "-static"'
```

**Comment by techknowlogick** [comment]
ah yup, that's it. I'm sorry that slipped my mind.
