### ISSUE TITLE
go get is deprecated in 1.17

### ISSUE THREAD

**Issue by vmasdani** [techknowlogick/xgo#134]
`go get` is deprecated in Go 1.17, and has to be replaced with `go install`.
 
![Screenshot from 2021-08-21 08-07-09](https://user-images.githubusercontent.com/37009464/130305983-bc9cc727-bc4a-4250-a080-825a32a5851d.png)

using this command, it's correct

```sh
go install src.techknowlogick.com/xgo@latest
```

I've made a PR here
https://github.com/techknowlogick/xgo/pull/133

**Comment by techknowlogick** [comment]
Thanks again for the PR, I've just merged it.
