### ISSUE TITLE
go: go.mod file not found in current directory or any parent directory

### ISSUE THREAD

**Issue by ntop001** [techknowlogick/xgo#143]
I had used xgo to build my project for a long time.  But two week ago, we upgrade from `karalabe/xgo` to `techknowlogick/xgo` , then I found all my project cannot compiled.

It gives the following errror:
```
Checking for required docker image techknowlogick/xgo:latest... found.
Cross compiling github.com/.../...
Building locally github.com/.../...
Compiling for linux/amd64...
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
2021/12/24 12:05:02 Failed to cross compile package: exit status 1.
```
My project is old styles Go project, and do not use go mod. So it's not a duplicated issue as #issue109 .  

My xgo version is :
```
➜  wsq git:(master) go install src.techknowlogick.com/xgo@latest                                                               
go: downloading src.techknowlogick.com/xgo v1.4.1-0.20211213020332-0df875d8b7b9
```

the command:
```
xgo --targets=linux/amd64 -out myapp ./
```

**Comment by ntop001** [comment]
I have just reinstall the `karalabe/xgo` and use it to build my project.  And rename `techknowlogick/xgo` to xxgo.

**Comment by techknowlogick** [comment]
As you are not using gomod, the behaviour in go has changed to use that, and so you have the option of explicitly passing an env var to disable go mod, or by just using the flag for xgo to use go 1.15 which is the lastest go version with the behaviour you are expecting
