### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by PulseBeat02** [techknowlogick/xgo#144]
Hi, I am having some troubles with xgo. I can't cross compile my Go project (https://github.com/MinecraftMediaLibrary/EzMediaCore-Native-Go). I have ran the commands to install the docker containers and the software, but I keep getting the same error:

The command I am running: `GO111MODULE=on /Users/bli24/go/bin/xgo github.com/MinecraftMediaLibrary/EzMediaCore-Native-Go`

Console Output:
```
bli24@macbook-air-2 Downloads % GO111MODULE=on /Users/bli24/go/bin/xgo github.com/MinecraftMediaLibrary/EzMediaCore-Native-Go 
Checking docker installation...
Client:
 Cloud integration: v1.0.22
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.10
 Git commit:        dea9396
 Built:             Thu Nov 18 00:36:09 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:39 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Checking for required docker image techknowlogick/xgo:latest... found.
Cross compiling github.com/MinecraftMediaLibrary/EzMediaCore-Native-Go...
Fetching main repository github.com/MinecraftMediaLibrary/EzMediaCore-Native-Go...
go: downloading github.com/MinecraftMediaLibrary/EzMediaCore-Native-Go v0.0.0-20211227013202-ebbb4e4c77c6
/build.sh: line 91: cd: /go/src/github.com/MinecraftMediaLibrary/EzMediaCore-Native-Go: No such file or directory
2021/12/28 17:05:30 Failed to cross compile package: exit status 1.
```

I tried for other repositories too such as the one provided in the README.md. I still get the same issue. I've searched through Github issues but I can't find a solution. Does anyone know what could be wrong here?

**Comment by techknowlogick** [comment]
Go is assuming that `github.com/MinecraftMediaLibrary/EzMediaCore-Native-Go` is the path. You could try `xgo ./`

**Comment by matthewmueller** [comment]
Thanks for this message, it solved my problem of wanting to cross-compile locally. I'd suggest adding this to the Readme since I almost gave up on xgo 😅

**Comment by techknowlogick** [comment]
@matthewmueller glad to hear :) yeah, docs definitely need updating.
