### ISSUE TITLE
Server certificate verification failed

### ISSUE THREAD

**Issue by thebaer** [techknowlogick/xgo#155]
I'm having trouble using xgo to compile my project, [WriteFreely](https://github.com/writefreely/writefreely). It only occurs when trying to pull dependencies from a git repository that uses a Let's Encrypt certificate. So based on the error message, I believe it's caused by the new Let's Encrypt root certificate changes from late last year, and the xgo Docker image not containing that.

Is there something I can do to work around this?

## Steps to reproduce

Get the `https://github.com/writefreely/writefreely` repository. Checkout `hotfix-0.13.2` branch.

Run this:

```
xgo --targets=linux/amd64 -go go-1.15.x -out writefreely ./cmd/writefreely
```

I get the following output:

```
Checking docker installation...
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Checking for required docker image techknowlogick/xgo:go-1.15.x... found.
Cross compiling github.com/writefreely/writefreely/cmd/writefreely...
Building locally github.com/writefreely/writefreely/cmd/writefreely...
Compiling for linux/amd64...
go: github.com/manifoldco/promptui@v0.8.0 requires
        gopkg.in/check.v1@v1.0.0-20180628173108-788fd7840127: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/9241c28341fcedca6a799ab7a465dd6924dc5d94044cbfabb75778817250adfc: exit status 128:
        fatal: unable to access 'https://gopkg.in/check.v1/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
2022/04/29 14:56:38 Failed to cross compile package: exit status 1.
```

**Comment by techknowlogick** [comment]
Thanks for this report @thebaer, especially all these details. Yeah, as you mentioned it's due to letsencrypt root cert update sept 30, 2021. However as go1.15 is EOL it's not being built anymore.

What happens when you try go1.18?

**Comment by thebaer** [comment]
I run into a previous bug [mentioned here](https://github.com/techknowlogick/xgo/issues/109#issuecomment-835494720)... Go 1.15 is the last version I could successfully build with.

**Comment by zeripath** [comment]
I think the go.mod issue should now be solved @thebaer
