### ISSUE TITLE
Cross Compiling to Mac M1

### ISSUE THREAD

**Issue by jhwz** [techknowlogick/xgo#159]
When I compile to mac M1, the resulting binary doesn't seem to run.

I assume the docker image is using osxcross? Another cross-compiler I tried, https://github.com/crazy-max/docker-osxcross would use o64-clang, when I think oa64-clang is required as the CC argument when compiling to `darwin/arm64`.

Am I missing something obvious? Does this buildchain work OK for others?

**Comment by techknowlogick** [comment]
So, M1s have "gatekeeper" protections, meaning the binaries need to be signed to be distributed. You can see the "codesign" cli commands to sign it without a valid developer key here: https://gitea.com/gitea/homebrew-gitea/src/branch/master/utils/macos_codesign.rb

This only works if you sign the binary on your own machine (although I only have one m1 device so I cant confirm this for sure), which means I can't bake the codesign util into the xgo container.
