### ISSUE TITLE
When compiling local module based package i get "unknown import path" error

### ISSUE THREAD

**Issue by jvsteiner** [techknowlogick/xgo#16]
I have a local module based code base with CGO dependancies, which builds on my host OS (OSX).  I am working with it outside the GOPATH which is why I am using this fork. My packages import path is, let's say, "github.com/foo/bar".  I have a cmd directory, with a "server" command, which would then be at "github.com/foo/bar/cmd/server".  My xgo command is something like:
```
xgo -targets=linux/amd64 -out dist/linux/hsmserver ./cmd/server
```
but it fails with:
```
can't load package: package github.com/foo/bar: unknown import path "github.com/foo/bar": cannot find module providing package github.com/foo/bar
```

**Comment by anjmao** [comment]
I have the same issue. It doesn't work because of this code https://github.com/techknowlogick/xgo/blob/master/docker/base/build.sh#L153

@techknowlogick I can fix it, could you let me know if you accept pull requests or should I create a new fork 😆

**Comment by kolaente** [comment]
@anjmao Sure, either @techknowlogick or I will review.

**Comment by kolaente** [comment]
@anjmao any updates?

**Comment by anjmao** [comment]
Hi @kolaente Sorry, for late response. I end up using my own fork since your fork doesn't support gomobile.

**Comment by anjmao** [comment]
In my fork I dropped support for old GOPATH based builds https://github.com/anjmao/xgo
There is docker image anjmao/xgo:go-1.13.1 on docker hub. Once I finish testing we could probably merge changes back to this repo.

**Comment by kolaente** [comment]
@anjmao That sounds awesome! We've been wanting to do this since Go 1.10 is eol.

**Comment by techknowlogick** [comment]
Yeah, we could probably drop gopath support now that we support a minimum of golang 1.13

**Comment by zeripath** [comment]
This may have been solved recently - please try again

**Comment by techknowlogick** [comment]
Closing, but please re open if issue remains
