### ISSUE TITLE
Upgrade to Ubuntu 20.04 or newer base image

### ISSUE THREAD

**Issue by silverwind** [techknowlogick/xgo#163]
xgo uses Ubuntu 18.04 which is [incompatible with things like Node.js 18](https://github.com/go-gitea/gitea/pull/20340#issuecomment-1183492951), a upgrade to Ubuntu 20.04 or 22.04 would be appreciated.

**Comment by RuboGubo** [comment]
This would most likely also fix #155

**Comment by zeripath** [comment]
IIRC The problem is ABI compatibility with different glibcs in particular CENTOS

**Comment by silverwind** [comment]
FWIW, Ubuntu 18.04 will reach EOL in April, after that, only the paid version will get security updates.

**Comment by techknowlogick** [comment]
> IIRC The problem is ABI compatibility with different glibcs in particular Centos 7 / RHEL7

Yeah, that's exactly the case. Last OS bump (from 16 to 18) caused gitea (and other projects that use XGO too) to fail on supported versions of CentOS/RHEL, and now that there is Rocky & Alma too that need to be worried about.

I'm not sure the best way forward, I'd of course like to bump to at least ubuntu20.04, but am worried about RHEL derivative support, and I don't know that the paid support version of 18.04 license would allow me to distribute it in such a way that xgo is currently.

I suspect the most likely way forward is for me to build a local build with the bumped OS and then test on various OSes.

**Comment by zeripath** [comment]
I wonder if there is a way we could actually build against musl instead of glibc thus avoiding the ABI issue?

**Comment by silverwind** [comment]
FWIW, Ubuntu 18.04 has now reached EOL.

**Comment by techknowlogick** [comment]
> FWIW, Ubuntu 18.04 has now reached EOL.

@silverwind I think we can do the upgrade now. I suspect there has been some movement away from CentOS 7 due to the change to stream.

**Comment by silverwind** [comment]
From what I know, most people have now migrated to Rocky or Alma. Officially CentOS 7 has still 1 year to go until EOL, but I don't see this so strict.

**Comment by techknowlogick** [comment]
Looking at https://en.wikipedia.org/wiki/Rocky_Linux and https://endoflife.date/rocky-linux Rocky 8 is supported until 2029 (at least for security support) and uses 4.x kernel. I'll need to do some testing to ensure that Gitea binaries still work on it before merging the change.

**Comment by silverwind** [comment]
They are all binary-compatible to RHEL8, so if it works on one, it will work on all.
