### ISSUE TITLE
Building with --pkg names the executable after the module instead of the package

### ISSUE THREAD

**Issue by darcys22** [techknowlogick/xgo#174]
My project defines the module in go.mod
```
module github.com/darcys22/godbledger
```
and I have subdirectories for each executable 
```
root
 - go.mod
 - godbledger/
   - main.go
 - reporter/
   - main.go 
```

When running xgo like this to build each executable using the `--pkg` parameter:
```
/home/sean/godbledger/build/bin/xgo --go=go-1.19.x --targets linux/386 --dest /home/sean/godbledger/build/dist/linux-386 -v --pkg reporter .
```

The name of the executable will be godbledger, not reporter
```
sean@sean-B550-AORUS-PRO-AX:~/godbledger/build/dist/linux-386/github.com/darcys22$ ls
godbledger-linux-386
```

It looks like the cause of this is in the `build.sh` where `$NAME` is changed if `$USEMODULES = true`
```
# Configure some global build parameters
NAME=`basename $1/$PACK`

# Go module-based builds error with 'cannot find main module'
# when $PACK is defined
if [[ "$USEMODULES" = true ]]; then
  NAME=`sed -n 's/module\ \(.*\)/\1/p' /source/go.mod`
fi
```

Unsure if I am using xgo incorrectly here (or even the modules structure tbh) but the readme makes it look like this should be the name of the executable

**Comment by zeripath** [comment]
So the code was recently changed, but it still effectively does the same thing.

Looking at this code again I agree this algorithm is incorrect, but it's not necessarily well defined as to what it should be.

I'll include a fix for this in the big PR I'm working on.
