### ISSUE TITLE
add cache

### ISSUE THREAD

**Issue by aadog** [techknowlogick/xgo#178]
add cache

**Comment by techknowlogick** [comment]
Hi @aadog, thank you for this issue. Could you describe what you are expecting if this ticket would be implemented?

**Comment by aadog** [comment]
This package is redownloaded every time, the dependency problem is a cache problem, same as https://github.com/techknowlogick/xgo/pull/116, but don't know why he is not removed?

**Comment by aadog** [comment]
@techknowlogick  What's the reason why he didn't merge successfully?

**Comment by techknowlogick** [comment]
Thanks. I will close this issue as a duplicate of https://github.com/techknowlogick/xgo/issues/108, and the discussion can continue there :)
