### ISSUE TITLE
Why xgo add /build/ prefix in front of module name? And goland IDE can not access this path in MAC

### ISSUE THREAD

**Issue by winer632** [techknowlogick/xgo#181]
my go module defination is 
module gitlab.bj.sensetime.com/ABG/senseinsight/edgebox/insight-admin
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/4931801/203002577-26e3ccf8-3fbb-46d4-8683-8bec7814fe82.png">

Why xgo add /build/ prefix in front of module name? And goland IDE can not access this path in MAC file system
The former version of xgo works well, this error appears only after I docker pull the latest docker image today

![image](https://user-images.githubusercontent.com/4931801/203002307-bb96db38-c610-471a-9c93-9f21d6a3a786.png)

**Comment by winer632** [comment]
My Makefile is like this, when I type _**make**_ it works well, but when I type **_make edge_** the error appears
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/4931801/203005772-9191666c-5f34-4802-8168-de78f082bd02.png">

**Comment by winer632** [comment]
finally find a workaround solution, but it's better xgo can solve the root cause
![image](https://user-images.githubusercontent.com/4931801/203047785-eb9481b1-2cea-48b9-bf8c-c26d010c24cf.png)

![image](https://user-images.githubusercontent.com/4931801/203048151-67a6830c-f773-4160-983a-e3f7fe9f37da.png)

**Comment by zeripath** [comment]
I think was related to a previous bug - which should be fixed but there's another in there that should be fixed by #194
