### ISSUE TITLE
Does not work for go1.20

### ISSUE THREAD

**Issue by gera2ld** [techknowlogick/xgo#197]
It seems that the script here assumes the version number is always composed of three numbers (e.g. `1.19.5`) but `1.20` is an exception:

https://github.com/techknowlogick/xgo/blob/ead5a0b64030fcaca9ea9ab2924bba5cd5eafb96/docker/build/build.sh#L57

As a result, `GO_VERSION_MINOR` gets an invalid value and the script throws an error:

```
#10 6.284 /build.sh: line 61: [[: go version go1.20 linux/amd64: syntax error: invalid arithmetic operator (error token is ".20 linux/amd64")
```

**Comment by techknowlogick** [comment]
@gera2ld thanks for issue. I've pushed 35ddcce, and hopefully that'll solve the issue. Please re-open/ping me if issue still continues :)

**Comment by gera2ld** [comment]
@techknowlogick thank you for the quick response.
But I'm afraid the fix doesn't work, because `GO_VERSION_MINOR` will be the original string instead of an empty value since the regexp doesn't match anything.

You can simply test it in the terminal:

```bash
$ echo go version go1.15.14 linux/amd64 | sed -e 's/.*go[0-9]\+\.\([0-9]\+\)\..*/\1/'
> 15

$ echo go version go1.20 linux/amd64 | sed -e 's/.*go[0-9]\+\.\([0-9]\+\)\..*/\1/'
> go version go1.20 linux/amd64
```

My proposal is to change the command as follows:

```diff
- GO_VERSION_MINOR=$(go version | sed -e 's/.*go[0-9]\+\.\([0-9]\+\)\..*/\1/')
+ GO_VERSION_MINOR=$(go version | sed -e 's/.*go[0-9]\+\.\([0-9]\+\)\b.*/\1/') 
```

**Comment by zeripath** [comment]
I'm really beginning to think that we might be better off changing build.sh into a build.go!

@gera2ld please do send a PR
