### ISSUE TITLE
I need to install libpcap-dev in the Images.how to operate.

### ISSUE THREAD

**Issue by qq790382720** [techknowlogick/xgo#210]
Build Command : xgo --targets=linux/arm .

Error:
hecking for required docker image techknowlogick/xgo:latest... found.
Cross compiling local repository: . : ...
Enabled Go module support
Building /source/go.mod...
Compiling for linux/arm-5...
/# github.com/google/gopacket/pcap
/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.
Cleaning up build environment...
Will,What am I supposed to do now

**Comment by techknowlogick** [comment]
You may need to use https://github.com/gopacket/gopacket instead as it looks to be a more up to date version of the gopacket library. In terms of adding the pcap c code, you could use the `--deps` argument. Something like `--deps=https://gmplib.org/download/gmp/gmp-6.1.0.tar.bz2`, but with the pcap code instead.

**Comment by bearsh** [comment]
another possibility is using hooks (`-hooksdir`), see also https://github.com/techknowlogick/xgo#hooks then you can install arbitrary pkg in you container (`apt install -y libpcap-dev`)

**Comment by qq790382720** [comment]
> Contributor

Can you give me an example? Thank you

**Comment by qq790382720** [comment]
> another possibility is using hooks (`-hooksdir`), see also https://github.com/techknowlogick/xgo#hooks then you can install arbitrary pkg in you container (`apt install -y libpcap-dev`)

Can you give me an example? Thank you

**Comment by bearsh** [comment]
create a directory, e.g. `.xgohooks` in your project's directory. place a file with the name `setup.sh` with following content in it:

```bash
apt update && apt install -y libpcap-dev
```

the call xgo with the following option:
`xgo -hooksdir .xgohooks ...`

**Comment by bearsh** [comment]
@qq790382720 did this work for you? can the issue be closed?

**Comment by techknowlogick** [comment]
I'll close this now, but please let me know if you need it re-opened :)
