### ISSUE TITLE
Add support for the headtype windowsgui

### ISSUE THREAD

**Issue by oSethoum** [techknowlogick/xgo#230]
Hi, am trying to cross compile my app and I wanna use it in windows without cmd, for that go support the headtype -H="windowsgui" with -ldflags, the build panics when I use it like this
```cmd 
 xgo -ldflags="-s -w -H windowsgui" -targets=windows/amd64,darwin/amd64,linux/amd64 --out=bin/server .
  ```

**Comment by bearsh** [comment]
maybe you should call xgo twice, once for the windows target with `-H windowsgui` and once for the other targets without it.

**Comment by oSethoum** [comment]
@bearsh I will try it and see, thank you.

**Comment by techknowlogick** [comment]
Yup, what @bearsh said. It'll otherwise try to apply to each build when windowsgui should(?) just be applied to the windows build.

**Comment by oSethoum** [comment]
@bearsh it worked, again thank you.
