### ISSUE TITLE
Error writing go.sum (read-only file system)

### ISSUE THREAD

**Issue by Smadarl** [techknowlogick/xgo#36]
I've been building without `go mod` for a while.  But after setting up `go mod`, I now get this error:

> Checking for required docker image build-kafka... found.
Cross compiling go-repo/consumers/sendactions...
Building locally go-repo/consumers/sendactions...
Compiling for linux/amd64...
go: writing go.sum: open /ext-go/1/src/go-repo/go.sum747278511.tmp: read-only file system
2019/09/11 15:45:50 Failed to cross compile package: exit status 1.

I tried changing permissions on my go.sum (666), and then tried renaming it, and I still get the same error.

**Comment by Smadarl** [comment]
Here's the Dockerfile for that image I'm using:

> FROM techknowlogick/xgo:latest
RUN git clone https://github.com/edenhill/librdkafka.git && cd librdkafka && ./configure && make && make install && cd .. && rm -rf librdkafka

**Comment by anjmao** [comment]
Hi @Smadarl, just run `go mod tidy` to update your go.mod, go.sum files. This works as expected as go build should not update go.sum file inside docker container.

**Comment by kolaente** [comment]
@Smadarl does running `go mod tidy` fix it?

**Comment by hunterlong** [comment]
Seems to be an issue on line: https://github.com/techknowlogick/xgo/blob/980bc3ce3f0919a2b02bf33e226d0efaa95cd3dd/xgo.go#L316

read only volume. I'm having same issue.

**Comment by techknowlogick** [comment]
Closing for now. Please re-open if you are still facing this issue.
