### ISSUE TITLE
Pass -trimpath flag to the Go toolchain

### ISSUE THREAD

**Issue by novabyte** [techknowlogick/xgo#37]
In Go 1.13 the `-trimpath` flag was added to strip the prefix from filesystem paths so that the resulting executable is filesystem layout independent. It looks like `xgo` does not offer a way to pass in custom compiler flags right now.

Should `-trimpath` become a flag recognised by `xgo` or should there be a way to add custom flags to the compiler?

**Comment by kolaente** [comment]
Is `-trimpath` a direct flag for `go build` or a gc option?

(Either way, supporting extra build flags sounds like a good idea)

**Comment by novabyte** [comment]
@kolaente It's a direct flag for the `go build` subcommand:

> remove all file system paths from the resulting executable.
> Instead of absolute file system paths, the recorded file names
> will begin with either "go" (for the standard library),
> or a module path@version (when using modules),
> or a plain import path (when using GOPATH).

It's only available on the Go 1.13 toolchain and is useful to create filesystem independent builds.

**Comment by kolaente** [comment]
Then we'll need to add this explicitly. Would you be able to send a pr? Hacktoberfest starts next week :slightly_smiling_face:

**Comment by novabyte** [comment]
@kolaente Done, I opened a pull request 👍

**Comment by kolaente** [comment]
Closing this, since the PR has been merged.
