### ISSUE TITLE
checkDockerImage can not find image

### ISSUE THREAD

**Issue by chy373** [techknowlogick/xgo#41]
I have docker image techknowlogick/xgo locally
![image](https://user-images.githubusercontent.com/5926064/66645057-0adad680-ec55-11e9-93ec-4b28a9eba219.png)

when I run xgo，I got this
![image](https://user-images.githubusercontent.com/5926064/66645119-33fb6700-ec55-11e9-88d0-ba0d60eeb10b.png)

and I check the source code
![image](https://user-images.githubusercontent.com/5926064/66645173-4e354500-ec55-11e9-9f7b-c823f1d8425f.png)
the image name has a goverison(default is latest) suffix, so xgo will not find the existed image whose name without the latest suffix

should we give this a PR?

**Comment by kolaente** [comment]
A PR would be great, yes!

**Comment by chy373** [comment]
@kolaente hi， I have sent a [PR](https://github.com/techknowlogick/xgo/pulls)
and there is another related problem with the go options in xgo command.
In xgo's readme, go option has no "go-" prefix.
![image](https://user-images.githubusercontent.com/5926064/67086386-30c32680-f1d3-11e9-9ef7-40cc5f07b735.png)
In dockerhub, xgo's tags has a "go-" prefix.   
![image](https://user-images.githubusercontent.com/5926064/67086502-7ed82a00-f1d3-11e9-9e7e-45cd806b6b0e.png)
so when use xgo with go options, if image is not found, docker pull will not work.
![image](https://user-images.githubusercontent.com/5926064/67086590-b1822280-f1d3-11e9-9d2f-2e686d1c27cf.png)
I think there are three solutions:
1. add a "go-"  prefix in readme
2. change tags of xgo images
3. do some trick in xgo.go to fix this

**Comment by kolaente** [comment]
Fixed with  #43

**Comment by chy373** [comment]
@kolaente hi，did you have a look at https://github.com/techknowlogick/xgo/issues/41#issuecomment-543655992，I think we should change the readme about go options also

**Comment by techknowlogick** [comment]
@chy373 could you send a PR for the readme changes?

**Comment by chy373** [comment]
> @kolaente hi， I have sent a [PR](https://github.com/techknowlogick/xgo/pulls)
> and there is another related problem with the go options in xgo command.
> In xgo's readme, go option has no "go-" prefix.
> ![image](https://user-images.githubusercontent.com/5926064/67086386-30c32680-f1d3-11e9-9ef7-40cc5f07b735.png)
> In dockerhub, xgo's tags has a "go-" prefix.
> ![image](https://user-images.githubusercontent.com/5926064/67086502-7ed82a00-f1d3-11e9-9e7e-45cd806b6b0e.png)
> so when use xgo with go options, if image is not found, docker pull will not work.
> ![image](https://user-images.githubusercontent.com/5926064/67086590-b1822280-f1d3-11e9-9d2f-2e686d1c27cf.png)
> I think there are three solutions:
> 
> 1. add a "go-"  prefix in readme
> 2. change tags of xgo images
> 3. do some trick in xgo.go to fix this

@kolaente I think this problem has not been solved, how about change [go releases part](https://github.com/techknowlogick/xgo#go-releases) of readme

**Comment by techknowlogick** [comment]
Closed with merged PR
