### ISSUE TITLE
Error "invalid mode: /build" on Windows 7

### ISSUE THREAD

**Issue by janflyborg** [techknowlogick/xgo#60]
This issue https://github.com/karalabe/xgo/issues/106 prevents people on Windows from running xgo and we have the same problem here. 

However, there is a two year old PR that solves the problem, so could this PR by any chance be applied here? The original repo seems more or less abandoned:

https://github.com/karalabe/xgo/pull/119

**Comment by techknowlogick** [comment]
Thanks for ticket :) I'm not on windows so I'm thankful that there are others who are able to alert me to issues that happen on other platforms.

I've just ported that PR over here to #61, and will merge once the CI passes.

**Comment by janflyborg** [comment]
Excellent! Thanks for the help.

Regards
    //Jan Flyborg
