### ISSUE TITLE
Allow export customs environments variables and local files

### ISSUE THREAD

**Issue by xhit** [techknowlogick/xgo#62]
Currently xgo can use a local path of the project and use the local `GOPATH` environment variable, but some require dependencies like this ibm driver: https://github.com/ibmdb/go_ibm_db

The driver requires some custom environments variables and set `CGO_CFLAGS`, `CGO_LDFLAGS` and `LD_LIBRARY_PATH` (linux) and `DYLD_LIBRARY_PATH` (darwin)

The path of the clidriver (the dependencies) can be in any path.

Is possible to export or set in docker other locals environments variables from xgo and read the local content like the project to build content?

How to deal with this to build the project in linux or darwin?

**Comment by techknowlogick** [comment]
Perhaps https://github.com/techknowlogick/xgo/pull/97 will aid this issue as well

**Comment by xhit** [comment]
Perfect, I will close this issue for avoid duplication. Issue #96 and PR #97 are the main now.

Thanks!
