### ISSUE TITLE
Go module support with vendor directory is apparently not working

### ISSUE THREAD

**Issue by LogicalChaos** [techknowlogick/xgo#66]
Create a main that uses a module
```go
package main

import (
        "fmt"

        "github.com/dustin/go-humanize"
)

func main() {
   fmt.Printf("%s\n", humanize.IBytes(100000))
}
```
Init and generate the vendor directory
```
go mod init
go mod vendor
```
Compile with xgo
```
GOPATH=~/go xgo -x -v -go go-1.14.2 --targets=darwin/amd64 .
```
Examine the output of xgo, you'll see that it fails to detect the use of modules by the lack of [Enabled Go module support](https://github.com/techknowlogick/xgo/blob/bb0faa36127318c0ff63f1380ebe3d3be6f0c021/xgo.go#L350) output and that the go modules are downloaded again. This is a big probem when private repo's are included in the module dependency list, as neither `GOPRIVATE` nor the vendor directory can be used.

Part of the problem is that the compile path is [normalized](https://github.com/techknowlogick/xgo/blob/bb0faa36127318c0ff63f1380ebe3d3be6f0c021/xgo.go#L259) which prevents the [directory stat](https://github.com/techknowlogick/xgo/blob/bb0faa36127318c0ff63f1380ebe3d3be6f0c021/xgo.go#L263) from working correctly.  Passing in the full path rather than `.` doesn't help. 

EDIT: The directory containing the module is at the location `~/go/src/github.com/<user name>/test`

**Comment by bearsh** [comment]
work for me but I don't use GOPATH (it there a reason to do so?)

1. create the mentioned main.go file
2. `go mod init something.com/something`  # module path is required outside GOPATH
3. `go mod vendor`
4. `xgo -x -v --targets=darwin/amd64 .`

**Comment by techknowlogick** [comment]
Closing as with go1.16 we use vendor dir & go mod w/ Gitea.
