### ISSUE TITLE
Docker images change too often

### ISSUE THREAD

**Issue by ficapy** [techknowlogick/xgo#70]
I use it almost every half month. But almost every time I use it, I have to re-execute ```docker pull techknowlogick/ xgo```. and it looks like Dockerfile is badly written. Having to download several gigabytes at a time.

This is very detrimental to a bad network. Hopefully it will improve.

**Comment by kolaente** [comment]
Unfortunatly, there is no way around the docker image being several gigabytes large as it needs to include all sdks for multiple platforms etc. We already shrunk it by removing support for mobile cross compilation.

If you have any suggestions on how to further reduce the size of the image, we're open for suggestions.

On the other hand maybe we could add a flag to not download the image if one already exists on the host.

**Comment by ficapy** [comment]
@kolaente Yeah, consider adding a flag to use an existing image. Instead of must use the latest images. Because for a stable project, it's fine to use a fixed version, not always the latest one.

**Comment by ficapy** [comment]
@kolaente I'm sorry, I saw the documentation, can use the -go option to select a fixed version so that can avoid downloading the latest version, thanks for your help!
