### ISSUE TITLE
darwin/386 support drop

### ISSUE THREAD

**Issue by jeronimo13** [techknowlogick/xgo#78]
What was the reason to drop darwin/386 support?

**Comment by techknowlogick** [comment]
@jeronimo13 based on golang dropping it.

**Comment by jeronimo13** [comment]
Unfortunately, I still need darwin/386. I saw that v1.0.0+1.14.6 version has darwin/386 support.
I've tried `go get -u src.techknowlogick.com/xgo@v1.0.0+1.14.6` but as far as I understand the heavy lifting is done in the docker and xgo is just an API to the container

Is there a way that I can still use it with `techknowlogick/xgo`?

**Comment by techknowlogick** [comment]
@jeronimo13 if you wish to run a previous version with darwin/386 support you can use xgo cli to pass the `-go` flag. eg. `xgo -go go-1.14.6 ....` assuming you are running CLI outside of a docker container.
