### ISSUE TITLE
docker: Error response from daemon: invalid mode: /go.

### ISSUE THREAD

**Issue by YiuTerran** [techknowlogick/xgo#83]
using latest images.

**Comment by leventov** [comment]
Hello @techknowlogick, do you have an insight about what can be causing this issue?

**Comment by techknowlogick** [comment]
Thank you for the repo. I don't have insight into this issue. @leventov or @YiuTerran are you able to provide a repeatable case where you can trigger this? even information such as OS, or repo you are using is helpful.

**Comment by YiuTerran** [comment]
I ran it on macOS. Now i have changed to use `musl-cross`, so I can't reproduce this problem now.

**Comment by bearsh** [comment]
I think this happens if, for some reasons, `GOPATH` is not set...

**Comment by techknowlogick** [comment]
Hopefully this has been resolved with most recent merge. Otherwise please re-open.
