### ISSUE TITLE
Support for ios/arm64 possible?

### ISSUE THREAD

**Issue by arinc9** [techknowlogick/xgo#88]
I want to compile a go project for iOS arm64 architecture. Original xgo has got support for iOS but the latest go version on it is too old.
Do you plan on adding support for ios/arm64?

**Comment by techknowlogick** [comment]
I’m am unable to add this back in myself, but am happy to accept a PR that adds it back.

**Comment by techknowlogick** [comment]
Closing as dupe of #55
