### ISSUE TITLE
darwin/arm64 (aka Mac M1) support - sponsors needed

### ISSUE THREAD

**Issue by techknowlogick** [techknowlogick/xgo#89]
Now that macs are transitioning to M1 (arm64) architecture xgo needs to be updated to support the new target.

I already have devices for many other platforms (linux arm6/7/8, darwin amd64, windows amd64), however to start to support the M1s I'll need a device to test on. 

I currently have a Github sponsors page https://github.com/sponsors/techknowlogick and I'll use any funds collected from there to purchase an M1 device. Tbh I'd get the cheapest option available (confirmed that the macmini m1 is cheapest).

I'll purchase the device once I receive enough funds. I'll announce once this threshold is matched in case you decide to only sponsor for that goal, and if I receive any extra I'll use those funds to support my OSS work.

**Comment by techknowlogick** [comment]
One sponsor now supporting 🎉

I've now started to review what needs to be done to add support for M1, but can't do any work until I can test my assumptions.

**Comment by tstromberg** [comment]
@techknowlogick - It isn't as good as local, but please let me know if remote access to a M1 Mac Mini would help.

**Comment by techknowlogick** [comment]
@tstromberg that is so kind! Thank you. It seems scaleway just launched M1 support so I can hopefully test using a temporary instance, but if that doesn't work out (if they have no stock) I will reach out to you 😄

**Comment by techknowlogick** [comment]
![Screen Shot 2021-02-18 at 3 21 13 PM](https://user-images.githubusercontent.com/164197/108416651-00433080-71fd-11eb-8897-9af024875d21.png)

So, I have some most excellent news!! Thanks to the work I did on #99 to increase the base-sdk version to support go1.16, darwin/arm64 support is now included. There are a few extra things needed when building for it, such as the target needs to be `darwin-10.15/arm64` (this means base SDK is 10.15 which includes arm64 support), as plain `darwin/arm64` will still try to use 10.11 as base version.
