### ISSUE TITLE
Need Help Setting: No $GOPATH is set or forwarded to xgo

### ISSUE THREAD

**Issue by reowens** [techknowlogick/xgo#92]
I can't find any documentation on this error and how to forward the GOPATH to xgo. Any help would be appreciated.

**Comment by techknowlogick** [comment]
Thanks for reporting this, are you able to provide a repeatable case for this, or even just more details on how you are running xgo?

**Comment by techknowlogick** [comment]
Closing, but please feel free to reopen if you are able to answer the above. Thanks :)

Hopefully now that GOPATH is being deprecated you won't need to worry about the COPATH anymore.
