### ISSUE TITLE
Support custom C library install script

### ISSUE THREAD

**Issue by makeworld-the-better-one** [techknowlogick/xgo#96]
Right now the README says that only C libraries that are based on configure and make can be used. It'd be nice if a script could be specified that would be used to build the library instead.

For example I am wondering about cross-compiling [gocv](https://github.com/hybridgroup/gocv) which requires the OpenCV library, which is built like so:

```
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} -D OPENCV_EXTRA_MODULES_PATH=$(TMP_DIR)opencv/opencv_contrib-$(OPENCV_VERSION)/modules -D BUILD_DOCS=OFF -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_opencv_java=OFF -D BUILD_opencv_python=NO -D BUILD_opencv_python2=NO -D BUILD_opencv_python3=NO -D ENABLE_VFPV2=ON -D WITH_JASPER=OFF -D OPENCV_GENERATE_PKGCONFIG=ON ..
$(MAKE) -j $(shell nproc --all)
$(MAKE) preinstall
```

**Comment by bearsh** [comment]
i would be nice to have a generic solution for a problem like this. One needs some libraries with a build system other then autotools, another one just need to install additional packages using the package manager.

one way of doing this would be to extend `build.sh` to source a script provided by the user. either before the loop over all targets (https://github.com/techknowlogick/xgo/blob/main/docker/base/build.sh#L180) or in that loop of both. 

`build.sh` could test if e.g. a `.xgo` directory exists and then source `setup.sh` before the loop and `build.sh` in the loop if existing
